services:
  wishlist:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://db:27017/wishlist
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mongo:latest
    volumes:
      - wishlist_mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: wishlist

volumes:
  wishlist_mongodb_data: