spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/wishlist
      database: wishlist
logging:
  level:
    root: INFO
    br.com.felipedean.wishlist: DEBUG
    org.springframework.data.mongodb: DEBUG