spring:
  server:
    port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus
          - info

  endpoint:
    health:
      show-details: always

  health:
    mongo:
      enabled: true